%%%%%%%%%%%%% General configuration%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% February 2021 
% Vittorio Minio

%%%%%%%%%%%%%%%VARIABLES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% params: user parameters
% h: UI graphics parameters
% h2: UI control parameters
% main_fig: Home figure 
% panel_color: colors of the panel 
% fig_color: colors of the figure
%%%%%%%%%%%h2.variables/params.variables%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% panel (*): panel of parameters
% radiobutton: radio button within a button group 
% radio: button group 
%-------------------------------- General settings
%--- General info
% coord: the path of the coordinate file (.mat) 
% iconcoord: coordinate file icon
% map: the path of the DEM file (.tif)
% iconmap: DEM file icon
% sta_ref: the name of the reference station 
% component: the name of the component/channel
% comp_chan: the station system used (component/channel)
%--- Data file
% data: the Input folder
% save: the Output folder
% icon: I/O icon
% outputformat: the format (.mat/.txt) of the output files 

%% General Setting panel
h.panel(1)= uipanel(mainfig,'visible','on','Position',[.235 .15 .74 .8]);
set(h.panel(1),'BackgroundColor',panel_color)

%% Create text boxes
%-------------------------------- General Info
uicontrol(h.panel(1),'Style','text', 'String','General Info',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .9 .4 .05],...
    'BackgroundColor',panel_color);


uicontrol(h.panel(1),'Style','text', 'String','Coordinate file',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .84 .24 .05],...
    'BackgroundColor',panel_color);

uicontrol(h.panel(1),'Style','text', 'String','Map file',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .77 .24 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(1),'Style','text', 'String','Station reference',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .70 .24 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(1),'Style','text', 'String','Component/Channel',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .63 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(1),'Style','text', 'String','Comp/Chan',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .56 .2 .05],...
    'BackgroundColor',panel_color);


%-------------------------------- Data file
uicontrol(h.panel(1),'Style','text', 'String','Data file',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .43 .5 .05],...
    'BackgroundColor',panel_color);

uicontrol(h.panel(1),'Style','text', 'String','Input Folder',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .36 .24 .05],...
    'BackgroundColor',panel_color);

uicontrol(h.panel(1),'Style','text', 'String','Output Folder',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .29 .24 .05],...
    'BackgroundColor',panel_color);


uicontrol(h.panel(1),'Style','text', 'String','Output Format',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .22 .24 .05],...
    'BackgroundColor',panel_color);

%% Create editable text 
%-------------------------------- General Info
h2.coord= uicontrol(h.panel(1),'Style','edit', 'String',params.coord,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .855 .6 .04],...
    'BackgroundColor','w');
h2.iconcoord= uicontrol(h.panel(1),'Style','pushbutton', 'String','',...
    'Cdata',icons.file,'Tag','coord',...
    'Units','normalized','Position',[.83 .855 .06 .04],...
    'callback',@folder_cbk);

h2.map= uicontrol(h.panel(1),'Style','edit', 'String',params.map,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .785 .6 .04],...
    'BackgroundColor','w');

h2.iconmap= uicontrol(h.panel(1),'Style','pushbutton', 'String','',...
    'Cdata',icons.file,'Tag','map',...
    'Units','normalized','Position',[.83 .785 .06 .04],...
    'callback',@folder_cbk);

h2.sta_ref= uicontrol(h.panel(1),'Style','edit', 'String',params.sta_ref,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .715 .6 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef1');

%-------------------------------- Data file
h2.data= uicontrol(h.panel(1),'Style','edit', 'String',params.data,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .375 .6 .04],...
    'BackgroundColor','w');

h2.save= uicontrol(h.panel(1),'Style','edit', 'String',params.save,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .305 .6 .04],...
    'BackgroundColor','w');


h2.icon(1)= uicontrol(h.panel(1),'Style','pushbutton', 'String','',...
    'Cdata',icons.folder,'Tag','data_folder',...
    'Units','normalized','Position',[.83 .375 .06 .04],...
    'callback',@folder_cbk);

h2.icon(2)= uicontrol(h.panel(1),'Style','pushbutton', 'String','',...
    'Cdata',icons.folder,'Tag','save_folder',...
    'Units','normalized','Position',[.83 .305 .06 .04],...
    'callback',@folder_cbk);

%% Add Radio buttons
%-------------------------------- General Info
%--- Output format
h2.radiobutton(1)= uibuttongroup(h.panel(1),'units','normalized','BackgroundColor',panel_color,...
    'bordertype','none','Position',[.24 .23 .5 .05]);

h2.radio(1) = uicontrol( h2.radiobutton(1), 'Style','Radio','String','.mat',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.1 0 .3 1],'HandleVisibility','off');
h2.radio(2) = uicontrol( h2.radiobutton(1), 'Style','Radio','String','.txt',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.5 0 .3 1],'HandleVisibility','off');

%--- Component
h2.radiobutton(3)= uibuttongroup(h.panel(1),'units','normalized','BackgroundColor',panel_color,...
    'bordertype','none','Position',[.22 .645 .6 .04]);

h2.radio(5) = uicontrol( h2.radiobutton(3), 'Style','Radio','String','Z',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.1 0 .15 1],'HandleVisibility','off');
h2.radio(6) = uicontrol( h2.radiobutton(3), 'Style','Radio','String','N',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.25 0 .15 1],'HandleVisibility','off');
h2.radio(7) = uicontrol( h2.radiobutton(3), 'Style','Radio','String','E',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.4 0 .15 1],'HandleVisibility','off');
h2.radio(10) = uicontrol( h2.radiobutton(3), 'Style','Radio','String','F',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.55 0 .15 1],'HandleVisibility','off');

%--- Station system
h2.radiobutton(4)= uibuttongroup(h.panel(1),'units','normalized','BackgroundColor',panel_color,...
    'bordertype','none','Position',[.22 .575 .6 .04]);
h2.radio(8) = uicontrol( h2.radiobutton(4), 'Style','Radio','String','Comp',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.1 0 .15 1],'HandleVisibility','off');
h2.radio(9) = uicontrol( h2.radiobutton(4), 'Style','Radio','String','Chan',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.25 0 .15 1],'HandleVisibility','off');

%% Saving parameters buttons

uicontrol(h.panel(1),'style','pushbutton', 'string','Default',...
    'ToolTipString','Load default setting','Tag','default1',...
    'units','normalized','position',[.1 .03 .18 .07], ...
    'callback',@default_cbk);

uicontrol(h.panel(1),'style','pushbutton', 'string','Latest',...
    'ToolTipString','Load latest setting','Tag','latest1',...
    'units','normalized','position',[.41 .03 .18 .07], ...
    'callback',@latest_cbk);

uicontrol(h.panel(1),'style','pushbutton', 'string','Save',...
    'ToolTipString','Save setting changes','Tag','save1',...
    'units','normalized','position',[.72 .03 .18 .07], ...
    'callback',@save_cbk);

%% Setting radio buttons values
if strcmp(params.outputformat,'.mat')
    set (h2.radio(1),'value',1);
    set (h2.radio(2),'value',0);
elseif strcmp(params.outputformat,'.txt')
    set (h2.radio(1),'value',0);
    set (h2.radio(2),'value',1);        
end

if strcmp(params.component,'Z')
    set (h2.radio(5),'value',1);
    set (h2.radio(6),'value',0);
    set (h2.radio(7),'value',0);
    set (h2.radio(10),'value',0);
elseif strcmp(params.component,'N')
    set (h2.radio(5),'value',0);
    set (h2.radio(6),'value',1);
    set (h2.radio(7),'value',0);
    set (h2.radio(10),'value',0);
elseif strcmp(params.component,'E')
    set (h2.radio(5),'value',0);
    set (h2.radio(6),'value',0);
    set (h2.radio(7),'value',1);
    set (h2.radio(10),'value',0);
elseif strcmp(params.component,'F')
    set (h2.radio(5),'value',0);
    set (h2.radio(6),'value',0);
    set (h2.radio(7),'value',0);
   set (h2.radio(10),'value',1);
end

if strcmp(params.comp_chan,'Comp')
    set (h2.radio(8),'value',1);
    set (h2.radio(9),'value',0);
elseif strcmp(params.comp_chan,'Chan')
    set (h2.radio(8),'value',0);
    set (h2.radio(9),'value',1);
end