%%%%%%%%%%%%% Preliminary analysis configuration%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% February 2021 
% Vittorio Minio

%%%%%%%%%%%%%%%VARIABLES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% params: user parameters
% h: UI graphics parameters
% h2: UI control parameters
% main_fig: Home figure 
% panel_color: colors of the panel 
% fig_color: colors of the figure
%%%%%%%%%%%h2.variables/params.variables%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% panel (*): panel of parameters
%-------------------------------- Preliminary analysis settings
%--- Spectral setting
% w_spec: the analysis window for the Spectrogram (s)
% np: the dimension of the spectrums
% f_high_pass: the frequency for the high-pass filter (Hz)
% n_sta: the maximum number of stations to use for the Spectral coherence
% spec_hour: the number of spectrums for each trace
%--- RMS setting
% w_rms: the analysis window for the RMS analysis (s)
% f1: the minimum frequency for the RMS analysis (Hz)
% f2: the maximum frequency for the RMS analysis (Hz)
% step_rms: the frequency step for the RMS analysis (Hz)
% factor: the temporal factor for the moving average of the RMS (hours) 
%--- Polarization setting
% w_pol: the analysis window for the polarization analysis (s)
% f1_pol: the minimum frequency for the polarization analysis (Hz)
% f2_pol: the maximum frequency for the polarization analysis (Hz)
% step_pol: the frequency step for the polarization analysis (Hz)
% factor_pol: the temporal factor for the moving average of the polarization attributes (hours)
%--- Detection setting
% wshort: the short-term window or the pre-trigger window (s)
% wlong: the long-term window or the post-trigger window (s)
% f1_det: the minimum frequency for the band-pass filter (Hz)
% f2_det: the maximum frequency for the band-pass filter (Hz)
% treshold: the threshold value of the detection
% f1_down:  the minimum frequency for the band-pass filter (Only Salped) (Hz)
% f2_down: the maximum frequency for the band-pass filter (Only Salped) (Hz)
% f1_up: the minimum frequency for the band-pass filter (Only Salped) (Hz)
% f2_up: the maximum frequency for the band-pass filter (Only Salped) (Hz)

%% Preliminary Analysis panel
h.panel(3)= uipanel(mainfig,'visible','off','Position',[.235 .15 .74 .8]);
set(h.panel(3),'BackgroundColor',panel_color)

%% Text boxes
%-------------------------------- Spectral setting
uicontrol(h.panel(3),'Style','text', 'String','Spectral setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .9 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Window (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .84 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Hann_points',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .78 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Nstations',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .66 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','High pass filter (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .72 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Nspec',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .60 .2 .05],...
    'BackgroundColor',panel_color);

%-------------------------------- RMS setting
uicontrol(h.panel(3),'Style','text', 'String','RMS setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .5 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Window (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .44 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F1 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .38 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F2 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .32 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Step (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .26 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Factor mean (h)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .20 .2 .05],...
    'BackgroundColor',panel_color);

%-------------------------------- Polarization setting
uicontrol(h.panel(3),'Style','text', 'String','Polarization setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.5 .9 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Window (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .84 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F1 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .78 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F2 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .72 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Step (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .66 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Factor mean (h)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .60 .2 .05],...
    'BackgroundColor',panel_color);
%-------------------------------- Detection setting
uicontrol(h.panel(3),'Style','text', 'String','Detection setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.5 .5 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','W short (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .44 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','W long (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .38 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F1 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .32 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F2 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .26 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','Threshold',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.5 .20 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F1_down (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .44 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F2_down (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .38 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F1_up (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .32 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(3),'Style','text', 'String','F2_up (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .26 .2 .05],...
    'BackgroundColor',panel_color);

%% Editable text 
%-------------------------------- Spectral setting
h2.w_spec= uicontrol(h.panel(3),'Style','edit', 'String',params.w_spec,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .855 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.np= uicontrol(h.panel(3),'Style','edit', 'String',params.np,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .795 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.n_sta= uicontrol(h.panel(3),'Style','edit', 'String',params.n_sta,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .675 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f_high_pass= uicontrol(h.panel(3),'Style','edit', 'String',params.f_high_pass,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .735 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.spec_hour= uicontrol(h.panel(3),'Style','edit', 'String',params.spec_hour,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .615 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');

%-------------------------------- RMS setting
h2.w_rms= uicontrol(h.panel(3),'Style','edit', 'String',params.w_rms,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .455 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f1= uicontrol(h.panel(3),'Style','edit', 'String',params.f1,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .395 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f2= uicontrol(h.panel(3),'Style','edit', 'String',params.f2,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .335 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.step_rms= uicontrol(h.panel(3),'Style','edit', 'String',params.step_rms,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .275 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.factor= uicontrol(h.panel(3),'Style','edit', 'String',params.factor,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .215 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');

%-------------------------------- Polarization setting
h2.w_pol= uicontrol(h.panel(3),'Style','edit', 'String',params.w_pol,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.72 .855 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f1_pol= uicontrol(h.panel(3),'Style','edit', 'String',params.f1_pol,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.72 .795 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f2_pol= uicontrol(h.panel(3),'Style','edit', 'String',params.f2_pol,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.72 .735 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.step_pol= uicontrol(h.panel(3),'Style','edit', 'String',params.step_pol,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.72 .675 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.factor_pol= uicontrol(h.panel(3),'Style','edit', 'String',params.factor_pol,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.72 .615 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');

%-------------------------------- Detection setting
h2.wshort= uicontrol(h.panel(3),'Style','edit', 'String',params.wshort,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.64 .455 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.wlong= uicontrol(h.panel(3),'Style','edit', 'String',params.wlong,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.64 .395 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f1_det= uicontrol(h.panel(3),'Style','edit', 'String',params.f1_det,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.64 .335 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f2_det= uicontrol(h.panel(3),'Style','edit', 'String',params.f2_det,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.64 .275 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.treshold= uicontrol(h.panel(3),'Style','edit', 'String',params.treshold,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.64 .215 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f1_down= uicontrol(h.panel(3),'Style','edit', 'String',params.f1_down,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.88 .455 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f2_down= uicontrol(h.panel(3),'Style','edit', 'String',params.f2_down,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.88 .395 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f1_up= uicontrol(h.panel(3),'Style','edit', 'String',params.f1_up,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.88 .335 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');
h2.f2_up= uicontrol(h.panel(3),'Style','edit', 'String',params.f2_up,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.88 .275 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef3');

%% Saving buttons
uicontrol(h.panel(3),'style','pushbutton', 'string','Default',...
    'ToolTipString','Load default setting','Tag','default3',...
    'units','normalized','position',[.1 .03 .18 .07], ...
    'callback',@default_cbk);

uicontrol(h.panel(3),'style','pushbutton', 'string','Latest',...
    'ToolTipString','Load latest setting','Tag','latest3',...
    'units','normalized','position',[.41 .03 .18 .07], ...
    'callback',@latest_cbk);

uicontrol(h.panel(3),'style','pushbutton', 'string','Save',...
    'ToolTipString','Save setting changes','Tag','save3',...
    'units','normalized','position',[.72 .03 .18 .07], ...
    'callback',@save_cbk);