%%%%%%%%%%%%% Instrumental configuration%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% February 2021 
% Vittorio Minio

%%%%%%%%%%%%%%%VARIABLES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% params: user parameters
% h: UI graphics parameters
% h2: UI control parameters
% main_fig: Home figure 
% panel_color: colors of the panel 
% fig_color: colors of the figure
%%%%%%%%%%%h2.variables/params.variables%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% panel (*): panel of parameters
% radiobutton: radio button within a button group 
% radio: button group
%-------------------------------- Instrumental settings
%--- Coordinate system/Beam Pattern setting
% coord_sys: the coordinate system (metrics/degrees)
% fmin: the minimum frequency for the Beam pattern analysis (Hz)
% fmax: the maximum frequency for the Beam pattern analysis(Hz)
% step: the frequency step for the Beam pattern analysis (Hz)
% smin: the minimum slowness for the Beam pattern analysis (s/km)
% smax: the miximum slowness for the Beam pattern analysis (s/km)
% ns: the dimensions of the square grid slowness for the Beam pattern analysis
%--- Instrument correction setting
% poles: the path of the instrumental response correction parameters (.mat)
% iconpoles: instrument response correction parameters file icon
% data2: the Input folder
% save2: the Output folder 
% icon: I/O icon

%% Instrumental panel
h.panel(2)= uipanel(mainfig,'visible','off','Position',[.235 .15 .74 .8]);
set(h.panel(2),'BackgroundColor',panel_color)



%% Text boxes
%-------------------------------- Coordinate system/Beam Pattern setting
uicontrol(h.panel(2),'Style','text', 'String','Coordinate system/Beam Pattern setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .92 .4 .05],...
    'BackgroundColor',panel_color);

uicontrol(h.panel(2),'Style','text', 'String','Coordinate Type',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .82 .2 .05],...
    'BackgroundColor',panel_color);

uicontrol(h.panel(2),'Style','text', 'String','Fmin (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .68 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Fmax (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.3 .68 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Step (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.55 .68 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Smin (s/km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.05 .61 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Smax (s/km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.3 .61 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Npoint',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.55 .61 .2 .05],...
    'BackgroundColor',panel_color);
%-------------------------------- Instrument correction setting
uicontrol(h.panel(2),'Style','text', 'String','Instrument correction setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .48 .4 .05],...
    'BackgroundColor',panel_color)
uicontrol(h.panel(2),'Style','text', 'String','Parameters',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.08 .38 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Input Folder',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.08 .31 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(2),'Style','text', 'String','Output Folder',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.08 .24 .2 .05],...
    'BackgroundColor',panel_color);
%% Editable text 
%-------------------------------- Coordinate system/Beam Pattern setting
h2.fmin= uicontrol(h.panel(2),'Style','edit', 'String',params.fmin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.15 .695 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
h2.fmax= uicontrol(h.panel(2),'Style','edit', 'String',params.fmax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.41 .695 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
h2.step= uicontrol(h.panel(2),'Style','edit', 'String',params.step,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.63 .695 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
h2.smin= uicontrol(h.panel(2),'Style','edit', 'String',params.smin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.15 .625 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
h2.smax= uicontrol(h.panel(2),'Style','edit', 'String',params.smax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.41 .625 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
h2.ns= uicontrol(h.panel(2),'Style','edit', 'String',params.ns,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.63 .625 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef2');
%-------------------------------- Instrument correction setting
h2.poles= uicontrol(h.panel(2),'Style','edit', 'String',params.poles,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .395 .6 .04],...
    'BackgroundColor','w');
h2.iconpoles= uicontrol(h.panel(2),'Style','pushbutton', 'String','',...
    'Cdata',icons.file,'Tag','poles',...
    'Units','normalized','Position',[.83 .395 .06 .04],...
    'callback',@folder_cbk);
h2.data2= uicontrol(h.panel(2),'Style','edit', 'String',params.data2,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .325 .6 .04],...
    'BackgroundColor','w');

h2.save2= uicontrol(h.panel(2),'Style','edit', 'String',params.save2,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .255 .6 .04],...
    'BackgroundColor','w');
h2.icon(3)= uicontrol(h.panel(2),'Style','pushbutton', 'String','',...
    'Cdata',icons.folder,'Tag','data2_folder',...
    'Units','normalized','Position',[.83 .325 .06 .04],...
    'callback',@folder_cbk);

h2.icon(4)= uicontrol(h.panel(2),'Style','pushbutton', 'String','',...
    'Cdata',icons.folder,'Tag','save2_folder',...
    'Units','normalized','Position',[.83 .255 .06 .04],...
    'callback',@folder_cbk);
%% Add Radio buttons
%-------------------------------- Coordinate system/Beam Pattern setting
%--- Geographic coordinate system UTM/WGS84
h2.radiobutton(2)= uibuttongroup(h.panel(2),'units','normalized','BackgroundColor',panel_color,...
    'bordertype','none','Position',[.2 .835 .7 .05]);

h2.radio(3) = uicontrol( h2.radiobutton(2), 'Style','Radio','String','m',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.1 0 .15 1],'HandleVisibility','off');
h2.radio(4) = uicontrol( h2.radiobutton(2), 'Style','Radio','String','degrees',...
    'BackgroundColor',panel_color, 'units','normalized','position',[.25 0 .15 1],'HandleVisibility','off');
%% Saving parameters buttons

uicontrol(h.panel(2),'style','pushbutton', 'string','Default',...
    'ToolTipString','Load default setting','Tag','default2',...
    'units','normalized','position',[.1 .03 .18 .07], ...
    'callback',@default_cbk);

uicontrol(h.panel(2),'style','pushbutton', 'string','Latest',...
    'ToolTipString','Load latest setting','Tag','latest2',...
    'units','normalized','position',[.41 .03 .18 .07], ...
    'callback',@latest_cbk);

uicontrol(h.panel(2),'style','pushbutton', 'string','Save',...
    'ToolTipString','Save setting changes','Tag','save2',...
    'units','normalized','position',[.72 .03 .18 .07], ...
    'callback',@save_cbk);


%% Setting radio buttons values
if strcmp(params.coord_sys,'m')
    set (h2.radio(3),'value',1);
    set (h2.radio(4),'value',0);
elseif strcmp(params.coord_sys,'degrees')
    set (h2.radio(3),'value',0);
    set (h2.radio(4),'value',1);
end