%%%%%%%%%%%%% Array analysis configuration%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% February 2021 
% Vittorio Minio

%%%%%%%%%%%%%%%VARIABLES%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% params: user parameters
% h: UI graphics parameters
% h2: UI control parameters
% main_fig: Home figure 
% panel_color: colors of the panel 
% fig_color: colors of the figure
%%%%%%%%%%%h2.variables/params.variables%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% panel (*): panel of parameters
%-------------------------------- Array analysis settings
%--- ZLC setting
% w_zlc: the analysis window for the ZLC analysis (s)
% f1_zlc: the minimum frequency for the ZLC analysis (Hz)
% f2_zlc: the maximum frequency for the ZLC analysis (Hz)
% step_zlc: the frequency step for the ZLC analysis (Hz)
% vel_zlc: the velocity value (km/s)
% splint: the Spline interpolation value (1 o 0)
% maxlags: the max lags for the Correlation coefficient calculation (samples)
%--- Radial Semblance/Semblance setting
% w_sem: the analysis window for the Radial Semblance/Semblance analysis (s)
% f0: the central frequency for the seismic amplitude decays with distance (Hz)
% Q: the quality factor for the seismic amplitude decays with distance 
% vel_sem: the velocity value (km/s)
% n_sem: the exponent value
% step_sem: the grid step size (km)
% topo_corr: the topographic correction (yes o no)
% freq_sem: the  frequency range for the band-pass filter (Hz)
% xmin: the minimum X-limit of the grid (km)
% xmax: the maximum X-limit of the grid (km)
% ymin: the minimum Y-limit of the grid (km)
% ymax: the maximum Y-limit of the grid (km)
% zmin: the minimum Z-limit of the grid (km)
% zmax: the maximum Z-limit of the grid (km)
%--- MUSIC setting
% freq0: the central frequency of the band of interest (Hz)
% nfreq: the number of frequencies of the band of interest
% m: the hamming value
% R: the R value
% pmax: the limit of the grid slowness (s/km) 
% pinc: the size step of the grid slowness (s/km) 
% ninicio: the time origin of the analysis window (s)  
% lwin: the analysis window for the MUSIC analysis (s) 
% advance: the advancement of the analysis window for the MUSIC analysis (%) 
% nsig: the number of source to use exclusively for the plotting

%% Array Analysis panel
h.panel(4)= uipanel(mainfig,'visible','off','Position',[.235 .15 .74 .8]);
set(h.panel(4),'BackgroundColor',panel_color)



%% Text boxes
%-------------------------------- Zero Lag Cross Correlation setting
uicontrol(h.panel(4),'Style','text', 'String','Zero Lag CrossCorrelation setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .9 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Window (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .84 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','F1 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .78 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','F2 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .72 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Step (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .66 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Velocity (km/s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .60 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Spline interpolation',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .54 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Max lags (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .48 .2 .05],...
    'BackgroundColor',panel_color);

%-------------------------------- Radial Semblance /Semblance setting
uicontrol(h.panel(4),'Style','text', 'String','Radial Semblance/Semblance setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.4 .9 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Window (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .84 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Cf (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .78 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Qf',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .72 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Velocity (km/s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .66 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Geometrical spreading',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .60 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Topographic correction',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .54 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Freq (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.4 .48 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Xlim 1 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .84 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Xlim 2 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .78 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Ylim 1 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .72 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Ylim 2 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .66 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Zlim 1 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .60 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Zlim 2 (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .54 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Step (km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.75 .48 .2 .05],...
    'BackgroundColor',panel_color);
%-------------------------------- MUSIC setting
uicontrol(h.panel(4),'Style','text', 'String','MUSIC setting',...
    'HorizontalAlignment','left','Fontweight','bold',...
    'Units','normalized','Position',[.01 .40 .4 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','F0 (Hz)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .34 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Nfreq',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .28 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Hamming points',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .22 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','R',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.01 .16 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Gridwidth (s/km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.38 .34 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Gridstep (s/km)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.38 .28 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','T0 (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.38 .22 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Win (s)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.38 .16 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Advance (%)',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.65 .34 .2 .05],...
    'BackgroundColor',panel_color);
uicontrol(h.panel(4),'Style','text', 'String','Nsig',...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.65 .28 .2 .05],...
    'BackgroundColor',panel_color);

%% Editable text 
%-------------------------------- Zero Lag Cross Correlation setting
h2.w_zlc= uicontrol(h.panel(4),'Style','edit', 'String',params.w_zlc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .855 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.f1_zlc= uicontrol(h.panel(4),'Style','edit', 'String',params.f1_zlc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .795 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.f2_zlc= uicontrol(h.panel(4),'Style','edit', 'String',params.f2_zlc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .735 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.step_zlc= uicontrol(h.panel(4),'Style','edit', 'String',params.step_zlc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .675 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.vel_zlc= uicontrol(h.panel(4),'Style','edit', 'String',params.vel_zlc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .615 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.splint= uicontrol(h.panel(4),'Style','edit', 'String',params.splint,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .555 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.maxlags= uicontrol(h.panel(4),'Style','edit', 'String',params.maxlags,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .495 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');

%-------------------------------- Radial Semblance /Semblance setting
h2.w_sem= uicontrol(h.panel(4),'Style','edit', 'String',params.w_sem,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .855 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.f0= uicontrol(h.panel(4),'Style','edit', 'String',params.f0,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .795 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.Q= uicontrol(h.panel(4),'Style','edit', 'String',params.Q,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .735 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.vel_sem= uicontrol(h.panel(4),'Style','edit', 'String',params.vel_sem,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .675 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.n_sem= uicontrol(h.panel(4),'Style','edit', 'String',params.n_sem,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .615 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.topo_corr= uicontrol(h.panel(4),'Style','edit', 'String',params.topo_corr,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .555 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.freq_sem= uicontrol(h.panel(4),'Style','edit', 'String',params.freq_sem,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.60 .495 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.xmin= uicontrol(h.panel(4),'Style','edit', 'String',params.xmin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .855 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.xmax= uicontrol(h.panel(4),'Style','edit', 'String',params.xmax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .795 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.ymin= uicontrol(h.panel(4),'Style','edit', 'String',params.ymin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .735 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.ymax= uicontrol(h.panel(4),'Style','edit', 'String',params.ymax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .675 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.zmin= uicontrol(h.panel(4),'Style','edit', 'String',params.zmin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .615 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.zmax= uicontrol(h.panel(4),'Style','edit', 'String',params.zmax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .555 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.step_sem= uicontrol(h.panel(4),'Style','edit', 'String',params.step_sem,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.86 .495 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');

%-------------------------------- MUSIC setting
h2.freq0= uicontrol(h.panel(4),'Style','edit', 'String',params.freq0,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .355 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.nfreq= uicontrol(h.panel(4),'Style','edit', 'String',params.nfreq,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .295 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.m= uicontrol(h.panel(4),'Style','edit', 'String',params.m,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .235 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.R= uicontrol(h.panel(4),'Style','edit', 'String',params.R,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.22 .175 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.pmax= uicontrol(h.panel(4),'Style','edit', 'String',params.pmax,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.52 .355 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.pinc= uicontrol(h.panel(4),'Style','edit', 'String',params.pinc,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.52 .295 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.ninicio= uicontrol(h.panel(4),'Style','edit', 'String',params.ninicio,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.52 .235 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.lwin= uicontrol(h.panel(4),'Style','edit', 'String',params.lwin,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.52 .175 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.advance= uicontrol(h.panel(4),'Style','edit', 'String',params.advance,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .355 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');
h2.nsig= uicontrol(h.panel(4),'Style','edit', 'String',params.nsig,...
    'HorizontalAlignment','left',...
    'Units','normalized','Position',[.76 .295 .1 .04],...
    'BackgroundColor','w','callback',@setdef,'Tag','setdef4');

%% Saving buttons
uicontrol(h.panel(4),'style','pushbutton', 'string','Default',...
    'ToolTipString','Load default setting','Tag','default4',...
    'units','normalized','position',[.1 .03 .18 .07], ...
    'callback',@default_cbk);

uicontrol(h.panel(4),'style','pushbutton', 'string','Latest',...
    'ToolTipString','Load latest setting','Tag','latest4',...
    'units','normalized','position',[.41 .03 .18 .07], ...
    'callback',@latest_cbk);

uicontrol(h.panel(4),'style','pushbutton', 'string','Save',...
    'ToolTipString','Save setting changes','Tag','save4',...
    'units','normalized','position',[.72 .03 .18 .07], ...
    'callback',@save_cbk);